### ISSUE TITLE
Add Miscreated module

### ISSUE THREAD

**Issue by Partiesplayin** [CubeCoders/AMPTemplates#334]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  https://config.getamp.sh/

## Game Information:

Game Title: Miscreated
How to obtain: https://store.steampowered.com/app/299740/Miscreated/
Suppoted OSs: Windows 7 64bit , Windows 10
Supports RCON/Console input? Yes

## I confirm:

- [ x] that I have searched for an existing module request for this application.
- [ x] that the server is an official server distributed by the games publishers/developers.
- [ x] that the server is available to the general public.
- [ x] that the server can be run headless (without a GUI).
- [ x] I have already attempted to create a configuration myself using the configuration tool at https://config.getamp.sh/

**Comment by Greelan** [comment]
Closed because repeats https://github.com/CubeCoders/AMPTemplates/issues/228

However, I did create a functioning template several months ago but never got any testing feedback from the user who requested it.

I can dust it off and you can have a look. I can't recall exactly what issues it had other than there was no console input or output in AMP (not uncommon unfortunately).

**Comment by Greelan** [comment]
Ghosted again it seems... 👀

**Comment by Partiesplayin** [comment]
Ghosted ?On Apr 15, 2023 5:52 PM, Greelan ***@***.***> wrote:
Ghosted again it seems... 👀

**Comment by Greelan** [comment]
I mean that I did not get any response from you.
